BetManager.Web/Controllers/AccountController.cs
using BetManager.Web.Controllers.Accounts.Detail;
using BetManager.Web.Controllers.Accounts.Login;
using BetManager.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace BetManager.Web.Controllers
{
    public class AccountController : Controller
    {
        public AccountController()
        {

        }

        // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Detail()
        {
            var identity = (ClaimsIdentity)User.Identity;
            IEnumerable<Claim> claims = identity.Claims;
            string sid = claims.First(x => x.Type == ClaimTypes.Sid).Value;

            var result = Handler.Get<DetailAccountBuilder>().Build(Convert.ToInt32(sid));

            return View(result.Model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Detail(DetailAccountViewModel data)
        {
            if (ModelState.IsValid)
            {
                var result = Handler.Get<DetailAccountHandler>().Handle(data);
                if ((bool)result.Data)
                {
                    ViewBag.Message = "Změny proběhly v pořádku, pravděpodobně se projeví až při příštím spuštění";
                    Session.Clear();

                    return View(data);
                }
                else
                {
                    ModelState.AddModelError("", "Problém");
                }
            }
            return View(data);
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginAccountViewModel data)
        {
            if (ModelState.IsValid)
            {
                var result = Handler.Get<LoginAccountHandler>().Handle(data);
                if ((bool)result.Data)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Neplatné přihlášení");
                }
            }

            return View(data);
        }

        public ActionResult Logout()
        {
            Handler.Get<LoginAccountHandler>().Logout();
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

BetManager.Web/Controllers/AdminController.cs
using BetManager.Web.Controllers.Admins.Jobs.Create;
using BetManager.Web.Mvc;
using System.Web.Mvc;

namespace BetManager.Web.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CreateJob()
        {
            var result = Handler.Get<CreateJobBuilder>().Build();
            return View(result.Model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateJob(CreateJobModel model)
        {
            var result = Handler.Get<CreateJobHandler>().Handle(model);
            return RedirectToAction("Index", "Admin");
        }
    }
}

BetManager.Web/Controllers/HomeController.cs
using BetManager.Core.Domains.Tips;
using BetManager.Web.Controllers.Tips.List;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BetManager.Web.Controllers
{
    [Authorize]
    public class HomeController : Mvc.BaseController
    {
        private readonly ITipManager _tipManager;

        public HomeController()
        {
            _tipManager = new TipManager();
        }

        // GET: Tip
        public ActionResult Index(TipListFilterViewModel filter)
        {
            var vm = new TipListViewModel();
            vm.Filter = filter;
            // UpdateModel(filter);

            if (filter.DateFrom == null && filter.DateTo == null)
            {
                filter.SetDefaultDashboard(UserIdentity);
            }

            sessionHelper.Remember(filter);
            return View(vm);
        }

        // GET: Tip/Details/5
        public ActionResult Detail(int id)
        {
            var tip = _tipManager.GetById(id);
            ViewBag.Title = "Tip :: " + tip.DisplayName;
            return View(tip);
        }
    }
}

BetManager.Web/Controllers/PredictionController.cs
using BetManager.Web.Controllers.Predictions.Detail;
using BetManager.Web.Controllers.Predictions.List;
using BetManager.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BetManager.Web.Controllers
{
    [Authorize]
    public class PredictionController : BaseController
    {
        /// <summary>
        /// Přehled odhadů
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public ActionResult Index(PredictionListFilterViewModel filter)
        {
            if (filter.DateFrom == null && filter.DateTo == null)
            {
                filter.SetDefault(UserIdentity);
            }
            sessionHelper.Remember(filter);
            var result = Handler.Get<PredictionListBuilder>().Build(filter);
            return View(result.Model);
        }

        public ActionResult Detail(int id)
        {
            var result = Handler.Get<PredictionDetailTipBuilder>().Build(id);
            return View(result.Model);
        }
    }
}

BetManager.Web/Controllers/TipController.cs
using BetManager.Web.Controllers.Tips.Detail;
using BetManager.Web.Controllers.Tips.List;
using BetManager.Web.Controllers.Tips.UnderUpper;
using BetManager.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BetManager.Web.Controllers
{
    [Authorize]
    public class TipController : BaseController
    {
        public ActionResult Index(TipListFilterViewModel filter)
        {
            if (filter.DateFrom == null && filter.DateTo == null)
            {
                filter.SetDefault(UserIdentity);
            }
            sessionHelper.Remember(filter);
            var result = Handler.Get<TipListBuilder>().Build(filter);
            return View(result.Model);
        }

        public ActionResult Detail(int id)
        {
            var result = Handler.Get<DetailTipBuilder>().Build(id);
            return View(result.Model);
        }

        public ActionResult UnderUpper(TipUnderUpperFilterViewModel filter)
        {
            if (filter.DateFrom == null && filter.DateTo == null)
            {
                filter.SetDefault(UserIdentity);
            }
            sessionHelper.Remember(filter);
            var result = Handler.Get<TipUnderUpperBuilder>().Build(filter);
            return View(result.Model);
        }
    }
}

BetManager.Web/Views/Admin/CreateJob.cshtml
@model BetManager.Web.Controllers.Admins.Jobs.Create.CreateJobModel

@{
    ViewBag.Title = "Založení jobu";
}

<div class="row">
  <h2>@ViewBag.Title</h2>
</div>

<div class="row">
  <p>
    @Html.ActionLink("Zpět do aministrace", "Index", "Admin", null, new { @class = "btn btn-primary" })
  </p>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateJobModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TournamentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TournamentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TournamentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateActual, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateActual, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateActual, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ksi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ksi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ksi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

BetManager.Web/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="row">
  <h2>@ViewBag.Title</h2>
</div>

@Html.ActionLink("Create job", "CreateJob", "Admin")

<a href="/hangfire">Hangfire</a>

BetManager.Web/Views/Home/Index.cshtml
@model BetManager.Web.Controllers.Tips.List.TipListViewModel

@{
    ViewBag.Title = "Dashboard";
}

@Styles.Render("~/Content/morris")

<div class="row">
  <h2>@ViewBag.Title</h2>
</div>

<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">
      <i class="fa fa-bar-chart-o fa-fw"></i> Zisk algoritmu
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div id="morris-area-chart"></div>
    </div>
    <!-- /.panel-body -->
  </div>
</div>

@Html.Partial("~/Views/Tip/_IndexFilter.cshtml", Model.Filter)

@Html.Partial("~/Views/Tip/_IndexList.cshtml", Model.Rows)


@section scripts {
  @Scripts.Render("~/bundles/morris")

  <script type="text/javascript">

      var update_size = function () {
          //var table = $('#example');
          //table.width(table.parent().width());
      }

      $(window).resize(function () {
          clearTimeout(window.refresh_size);
          window.refresh_size = setTimeout(function () { update_size(); }, 250);
      });

      $(document).ready(function () {

          function changeDate(date) {
              return date.split(".").reverse().join("-");
          }

          $('#datepickerFrom').datetimepicker({
              locale: 'cs',
              format: 'L'
          });

          $('#datepickerTo').datetimepicker({
              locale: 'cs',
              format: 'L'
          });

          window.graphDate = changeDate($("#DateTo").val());

          var datatable = $('#example').DataTable({
              responsive: true,
              "AutoWidth": true,
              "serverSide": false,
              "processing": true,
              "pagingType": "simple",
              "ajax": {
                  url: "/api/tip",
                  type: "POST",
                  dataSrc: "",
                  data: function () {
                      return {
                          DateFrom: window.graphDate,
                          DateTo: window.graphDate,
                          Category: $("#Category").val(),
                          Odd: $("#Odd").val().replace(",", ".")
                      }
                  },
              },
              "columns": [
                { data: "DisplayName" },
                { data: "DateStart", render: function (d, t, r) { return moment(r.DateStart).format("YYYY-MM-DD HH:mm"); } },
                { data: "Home", render: function (d, t, r) { return '<button type="button" class="btn btn-sm" data-toggle="tooltip" data-placement="top" title="' + r.HomeOdd.toFixed(2) + '" >' + r.Home.toFixed(1) + '</button>' } },
                { data: "Draw", render: function (d, t, r) { return '<button type="button" class="btn btn-sm" data-toggle="tooltip" data-placement="top" title="' + r.DrawOdd.toFixed(2) + '" >' + r.Draw.toFixed(1) + '</button>' } },
                { data: "Away", render: function (d, t, r) { return '<button type="button" class="btn btn-sm" data-toggle="tooltip" data-placement="top" title="' + r.AwayOdd.toFixed(2) + '" >' + r.Away.toFixed(1) + '</button>' } },
                { data: "HomeOdd" },
                { data: "DrawOdd" },
                { data: "AwayOdd" },
                { data: "FirstValue" },
                { data: "Xvalue" },
                { data: "SecondValue" },
                { data: "Category" },
                { data: "PredictTip" },
                { data: "Odd" },
                { data: "WinnerCode" },
                { data: "ID" , render: function (d, t, r) { return '<a href="/Tip/Detail/' + r.ID + '" class="btn btn-primary">Detail</a>' } },
              ],
              "order": [[1, "asc"]],
              createdRow: function (row, data, dataIndex) {
                  // podbarveni radku
                  var isEqual = data.WinnerCode == data.PredictTip;
                  if (data.WinnerCode > 0 && data.PredictTip > 0) {
                      if (isEqual) {
                          $(row).addClass('success');
                      }
                      else {
                          $(row).addClass('danger');
                      }
                  }
                  // vyber tipu
                  var cssType = data.WinnerCode > 0 ? (isEqual ? 'btn-success' : 'btn-danger') : 'btn-info';
                  if (data.PredictTip == 1) {
                      $('td', row).eq(2).find(":button").addClass(cssType);
                  }
                  else if (data.PredictTip == 3) {
                      $('td', row).eq(3).find(":button").addClass(cssType);
                  }
                  else if (data.PredictTip == 2) {
                      $('td', row).eq(4).find(":button").addClass(cssType);
                  }

                  // pokud neni tip, tak zlute podbarvim viteze
                  if (data.WinnerCode > 0 && !isEqual) {
                      cssType = 'btn-warning';
                      if (data.WinnerCode == 1) {
                          $('td', row).eq(2).find(":button").addClass(cssType);
                      }
                      else if (data.WinnerCode == 3) {
                          $('td', row).eq(3).find(":button").addClass(cssType);
                      }
                      else if (data.WinnerCode == 2) {
                          $('td', row).eq(4).find(":button").addClass(cssType);
                      }
                  }
              }
          });

          var chart = Morris.Line({
              element: 'morris-area-chart',
              xkey: 'DateStart',
              ykeys: ['Total', 'Correct', 'Price'],
              labels: ['Tipů', 'Odhadnuto', 'Zisk'],
              pointSize: 2,
              hideHover: 'auto',
              dateFormat: function (x) { return moment(x).format("YYYY-MM-DD"); },
              resize: true
          }).on('click', function (i, row) {
              window.graphDate = row.DateStart;
              datatable.ajax.reload();
          });

          $.ajax({
              type: "POST",
              url: "/api/graphtip",

              data: {
                  DateFrom: changeDate($("#DateFrom").val()),
                  DateTo: changeDate($("#DateTo").val()),
                  Category: $("#Category").val(),
                  Odd: $("#Odd").val().replace(",", ".")
              },
              success: function (data) {
                  if (data) {
                      chart.setData(data);
                  }
              }
          });
      });
  </script>
}

BetManager.Web/Views/Shared/_LayouLogin.cshtml
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title - BetManager</title>
  @Styles.Render("~/Content/css")
  @Styles.Render("~/Content/datatables")
  @Styles.Render("~/Content/font-awesome")
  @Scripts.Render("~/bundles/modernizr")

  <script>
      (function (i, s, o, g, r, a, m) {
          i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
              (i[r].q = i[r].q || []).push(arguments)
          }, i[r].l = 1 * new Date(); a = s.createElement(o),
          m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
      })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

      ga('create', 'UA-72854012-3', 'auto');
      ga('send', 'pageview');

  </script>
</head>
<body>
  <div class="container">
    @RenderBody()
  </div>

  <footer class="footer">
    <div class="container">
      <br />
        <p class="pull-right">&copy; @DateTime.Now.Year - lorenzo.cz (@ViewContext.Controller.GetType().Assembly.GetName().Version)</p>
    </div>
  </footer>


  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/bootstrap")
  @Scripts.Render("~/bundles/datatables")

  @RenderSection("scripts", required: false)
</body>
</html>

BetManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title - BetManager</title>
  @Styles.Render("~/Content/css")
  @Styles.Render("~/Content/datatables")
  @Styles.Render("~/Content/metisMenu")
  @Styles.Render("~/Content/sb")
  @Styles.Render("~/Content/font-awesome")
  @Scripts.Render("~/bundles/modernizr")

  <script>
      (function (i, s, o, g, r, a, m) {
          i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
              (i[r].q = i[r].q || []).push(arguments)
          }, i[r].l = 1 * new Date(); a = s.createElement(o),
          m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
      })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

      ga('create', 'UA-72854012-3', 'auto');
      ga('send', 'pageview');

  </script>
</head>
<body>
  <div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("BetManager", "Index", "Home", null, new { @class = "navbar-brand" })
        @*<a class="navbar-brand" href="index.html">BetManager</a>*@
      </div>
      <!-- /.navbar-header -->
      <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-user">
            <li>
              <a href="@Url.Action("Detail", "Account")"><i class="fa fa-user fa-fw"></i> Profil</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="@Url.Action("Logout", "Account")"><i class="fa fa-sign-out fa-fw"></i> Odhlásit</a>
            </li>
          </ul>
          <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
      </ul>
      <!-- /.navbar-top-links -->
      <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
          <ul class="nav" id="side-menu">
            <li>
              <a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard fa-fw" aria-hidden="true"></i> Dashboard</a>
            </li>
            <li>
              <a href="@Url.Action("Index", "Tip")"><i class="fa fa-soccer-ball-o fa-fw" aria-hidden="true"></i> Tipy 1x2</a>
            </li>
            <li>
              <a href="@Url.Action("UnderUpper", "Tip")"><i class="fa fa-soccer-ball-o fa-fw" aria-hidden="true"></i> Tipy nad/pod</a>
            </li>
            <li>
              @if (User.Identity.Name == "admin")
              {
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Generování <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li>
                      <a href="/api/ImportData/Yesterday" target="_blank"><i class="fa fa-refresh fa-fw" aria-hidden="true"></i> Generuj včerejšek</a>
                    </li>
                    <li>
                      <a href="/api/ImportData/Tomorrow" target="_blank"><i class="fa fa-refresh fa-fw" aria-hidden="true"></i> Generuj zítřek</a>
                    </li>
                    <li>
                      <a href="/api/Prediction" target="_blank"><i class="fa fa-refresh fa-fw" aria-hidden="true"></i> Generuj odhady do tipů</a>
                    </li>
                    <li>
                      <a href="/admin" target="_blank"><i class="fa fa-refresh fa-fw" aria-hidden="true"></i> Admin část</a>
                    </li>
                  </ul>
                </li>
              }
            </ul>
          </div>
          <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
      </nav>
      <div id="page-wrapper">
        @RenderBody()
        <hr />
        <footer class="pull-right">
          <p>&copy; @DateTime.Now.Year - &copy; lorenzo.cz (@ViewContext.Controller.GetType().Assembly.GetName().Version)</p>
        </footer>
      </div>
    </div>
    <!-- /#wrapper -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/bundles/metisMenu")
    @Scripts.Render("~/bundles/sb")

  <script>
      $(document).ready(function () {
          $('[data-toggle="tooltip"]').tooltip();
          $('body').tooltip({ selector: '[data-toggle="tooltip"]' });
      });
  </script>
    @RenderSection("scripts", required: false)
  </body>
</html>

BetManager.Web/Views/Tip/Index.cshtml
@model BetManager.Web.Controllers.Tips.List.TipListViewModel

@{
    ViewBag.Title = "Tipy 1x2";
}

<div class="row">
  <h2>@ViewBag.Title</h2>
</div>
@Html.Partial("_IndexFilter", Model.Filter)

@Html.Partial("_IndexList", Model.Rows)

@section scripts {
  <script type="text/javascript">

      var update_size = function () {
          var table = $('#example');
          table.width(table.parent().width());
      }

      $(window).resize(function () {
          clearTimeout(window.refresh_size);
          window.refresh_size = setTimeout(function () { update_size(); }, 250);
      });

      $(document).ready(function () {
          $('#datepickerFrom').datetimepicker({
              locale: 'cs',
              format: 'L'
          });

          $('#datepickerTo').datetimepicker({
              locale: 'cs',
              format: 'L'
          });

          $('#example').DataTable({
              responsive: true,
              order: [[1, "asc"]],
              "pagingType": "simple",
              "AutoWidth": true,
              columns: [
                { data: "DisplayName" },
                { data: "DateStart", render: function (d, t, r) { return moment(r.DateStart).format("YYYY-MM-DD HH:mm"); } },
                { data: "Home", render: function (d, t, r) { return '<button type="button" class="btn btn-sm" data-toggle="tooltip" data-placement="top" title="' + r.HomeOdd + '" >' + r.Home + '</button>' } },
                { data: "Draw", render: function (d, t, r) { return '<button type="button" class="btn btn-sm" data-toggle="tooltip" data-placement="top" title="' + r.DrawOdd + '" >' + r.Draw + '</button>' } },
                { data: "Away", render: function (d, t, r) { return '<button type="button" class="btn btn-sm" data-toggle="tooltip" data-placement="top" title="' + r.AwayOdd + '" >' + r.Away + '</button>' } },
                { data: "HomeOdd" },
                { data: "DrawOdd" },
                { data: "AwayOdd" },
                { data: "FirstValue" },
                { data: "Xvalue" },
                { data: "SecondValue" },
                { data: "Category" },
                { data: "PredictTip" },
                { data: "Odd" },
                { data: "WinnerCode" },
                { data: "ID" }
              ],
              createdRow: function (row, data, dataIndex) {
                  // podbarveni radku
                  var isEqual = data.WinnerCode == data.PredictTip;
                  if (data.WinnerCode > 0 && data.PredictTip > 0) {
                      if (isEqual) {
                          $(row).addClass('success');
                      }
                      else {
                          $(row).addClass('danger');
                      }
                  }
                  // vyber tipu
                  var cssType = data.WinnerCode > 0 ? (isEqual ? 'btn-success' : 'btn-danger') : 'btn-info';
                  if (data.PredictTip == 1) {
                      $('td', row).eq(2).find(":button").addClass(cssType);
                  }
                  else if (data.PredictTip == 3) {
                      $('td', row).eq(3).find(":button").addClass(cssType);
                  }
                  else if (data.PredictTip == 2) {
                      $('td', row).eq(4).find(":button").addClass(cssType);
                  }
                  // pokud neni tip, tak zlute podbarvim viteze
                  if (data.WinnerCode > 0 && !isEqual) {
                      cssType = 'btn-warning';
                      if (data.WinnerCode == 1) {
                          $('td', row).eq(2).find(":button").addClass(cssType);
                      }
                      else if (data.WinnerCode == 3) {
                          $('td', row).eq(3).find(":button").addClass(cssType);
                      }
                      else if (data.WinnerCode == 2) {
                          $('td', row).eq(4).find(":button").addClass(cssType);
                      }
                  }
              }
          });
      });
  </script>
}

BetManager.Web/Views/Tip/_DetailGoal.cshtml
@model IEnumerable<BetManager.Web.Controllers.Tips.Detail.DetailTipGoalViewModel>

<div class="table-responsive">
  <table id="example" class="table table-striped table-bordered table-hover text-center text-nowrap">
    <thead>
      <tr>
        @foreach (var item in Model)
        {
            <td>
              <strong>
                @Html.DisplayFor(modelItem => item.Id)
              </strong>
            </td>
        }
      </tr>
    </thead>
    <tbody>
      <tr>
        @foreach (var item in Model)
        {
            <td class="text-right">
              @Html.DisplayFor(modelItem => item.Prob) %
            </td>
        }
      </tr>
    </tbody>
  </table>
</div>

BetManager.Web/Views/Tip/_DetailPoisson.cshtml
@model IEnumerable<BetManager.Web.Controllers.Tips.Detail.DetailTipPoissonViewModel>

<div class="table-responsive">
  <table id="example" class="table table-striped table-bordered table-hover text-nowrap text-center">
    <thead>
      <tr>
        <td>
          <strong>
            @Html.DisplayNameFor(model => model.DisplayName)
          </strong>
        </td>
        <td>
          <strong>
            @Html.DisplayNameFor(model => model.GoalZero)
          </strong>
        </td>
        <td >
          <strong>
            @Html.DisplayNameFor(model => model.GoalOne)
          </strong>
        </td>
        <td>
          <strong>
            @Html.DisplayNameFor(model => model.GoalTwo)
          </strong>
        </td>
        <td>
          <strong>
            @Html.DisplayNameFor(model => model.GoalThree)
          </strong>
        </td>
        <td>
          <strong>
            @Html.DisplayNameFor(model => model.GoalFour)
          </strong>
        </td>
        <td>
          <strong>
            @Html.DisplayNameFor(model => model.GoalFive)
          </strong>
        </td>
        <td>
          <strong>
            @Html.DisplayNameFor(model => model.Tip)
          </strong>
        </td>
        <td>
          <strong>
            @Html.DisplayNameFor(model => model.Score)
          </strong>
        </td>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model)
      {
          <tr>
            <td>
              @Html.DisplayFor(modelItem => item.DisplayName)
            </td>
            <td class="text-right">
              @Html.DisplayFor(modelItem => item.GoalZero) %
            </td>
            <td class="text-right">
              @Html.DisplayFor(modelItem => item.GoalOne) %
            </td>
            <td class="text-right">
              @Html.DisplayFor(modelItem => item.GoalTwo) %
            </td>
            <td class="text-right">
              @Html.DisplayFor(modelItem => item.GoalThree) %
            </td>
            <td class="text-right">
              @Html.DisplayFor(modelItem => item.GoalFour) %
            </td>
            <td class="text-right">
              @Html.DisplayFor(modelItem => item.GoalFive) %
            </td>
            <td class="text-center info">
              <strong>@Html.DisplayFor(modelItem => item.Tip)</strong>
            </td>
            <td class="text-center">
              @Html.DisplayFor(modelItem => item.Score)
            </td>
          </tr>
      }
    </tbody>
  </table>
</div>